apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-repo
  namespace: flux
spec:
  interval: 1m
  url: https://github.com/ghj-dev/ci-cd.git
  secretRef:
    name: flux-git-deploy
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux
spec:
  interval: 10m
  path: "./deploy/k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-repo
  validation: client
